# This config file is used by ros2_control
controller_manager:
  ros__parameters:
    update_rate: 100  # Hz

    mycobot_arm_controller:
      type: joint_trajectory_controller/JointTrajectoryController


    joint_state_broadcaster:
      type: joint_state_broadcaster/JointStateBroadcaster

mycobot_arm_controller:
  ros__parameters:
    joints:
      - mycobot_joint_1
      - mycobot_joint_2
      - mycobot_joint_3
      - mycobot_joint_4
      - mycobot_joint_5
      - mycobot_joint_6
    command_interfaces:
      - position
    state_interfaces:
      - position
      - velocity