# MoveIt uses this configuration for controller management

moveit_controller_manager: moveit_simple_controller_manager/MoveItSimpleControllerManager

moveit_simple_controller_manager:
  controller_names:
    - moiro_arm_controller

  moiro_arm_controller:
    type: FollowJointTrajectory
    action_ns: follow_joint_trajectory
    default: true
    joints:
      - mycobot_joint_1
      - mycobot_joint_2
      - mycobot_joint_3
      - mycobot_joint_4
      - mycobot_joint_5
      - mycobot_joint_6